### ISSUE TITLE
DateTime64 conversion logic

### ISSUE THREAD

**Issue by subkanthi** [Altinity/clickhouse-sink-connector#232]
When the new records are inserted, 

DATETIME, DATETIME(0), DATETIME(1), DATETIME(2), DATETIME(3) | INT64 | io.debezium.time.TimestampRepresents the number of milliseconds past the epoch and does not include time zone information.
-- | -- | --
DATETIME(4), DATETIME(5), DATETIME(6) | INT64 | io.debezium.time.MicroTimestampRepresents the number of microseconds past the epoch and does not include time zone information.

- Make sure the data is not lost.(precision)
- Make sure the limits are set correctly on CH(since MySQL and CH limits are different)
- timezone is retained correctly.

**Comment by Selfeer** [comment]
The issue was verified by the Altinity QA team and marked as `qa-verified`.

Build used for testing: `altinityinfra/clickhouse-sink-connector:464-c979a8c2583ff701dd5b63efb8f36f7fff8111e7-lt`

Automated TestFlows tests were added to the develop branch:
https://github.com/Altinity/clickhouse-sink-connector/blob/develop/sink-connector-lightweight/tests/integration/tests/datatypes.py

Requirements for the ClickHouse Sink Connector Lightweight were updated.
