### ISSUE TITLE
Correctly handle temporal type Time zone.

### ISSUE THREAD

**Issue by aadant** [Altinity/clickhouse-sink-connector#328]
A MySQL Datetime is similar to a String, it is not dependent of the server time zone.
A MySQL Timestamp is similar to a DateTime in CH, it is dependent of the server time zone.

How to reproduce :

1. 

in MySQL, set 

```
time_zone=America/Chicago
```
in the my.cnf

in CH, set 

```
<timezone>America/Chicago</timezone>
```

2. 

Replicate https://github.com/Altinity/clickhouse-sink-connector/blob/develop/sink-connector/tests/data_types.sql

3. 

Compare the temporal tables. As the server time zones are the same, the DateTime and Timestamps should return the same values.

see also https://github.com/Altinity/clickhouse-sink-connector/issues/312
https://github.com/ClickHouse/ClickHouse/issues/7083

Using clickhouse-client, casting a CSV file containing data to a String on the client side creates a DateTime matching the original String on the server side.  If the client time zone is different and the String is cast to a DateTime on the client, the DateTime will not match the original String.

**Comment by Selfeer** [comment]
The issue was manually verified by the Altinity QA team and marked as `qa-verified`.

Build used for testing: `altinityinfra/clickhouse-sink-connector:443-14a14ba5c18fb3bc9f57c48d9a5079d4d6fe15e8-lt`

We've verified that the `DateTime` and `Timestamps` return the same value for the scenario when the ClickHouse and MySQL servers have the same timezone set but the main machine on which the servers are being run has a different timezone.
