### ISSUE TITLE
Config variable to start the sink-connector without turning on replication

### ISSUE THREAD

**Issue by aadant** [Altinity/clickhouse-sink-connector#353]
see https://dev.mysql.com/doc/refman/8.0/en/replication-options-replica.html#option_mysqld_skip-slave-start

```
skip_replica_start: True (default False)
```

**Comment by BorisTyshkevich** [comment]
@aadant please describe the use case when it is important.

**Comment by aadant** [comment]
@BorisTyshkevich : suppose you just restored a MySQL snapshot from MySQL with a binary log position or a GTID position.
If you start the sink-connector, you need to specify that position. Otherwise the position will be undefined.

**Comment by subkanthi** [comment]
Implemented in #379

**Comment by Selfeer** [comment]
The issue was manually verified by the Altinity QA team and marked as `qa-verified`.

Build used for testing: `altinityinfra/clickhouse-sink-connector:443-14a14ba5c18fb3bc9f57c48d9a5079d4d6fe15e8-lt`

We've verified that modifying `skip_replica_start` configuration and setting it to `true` skips the replication on startup.
