### ISSUE TITLE
sink connector cannot insert data into table named transaction

### ISSUE THREAD

**Issue by svyatalive** [Altinity/clickhouse-sink-connector#413]
The connector creates a table, but cannot insert data into it. Is it possible to set a different name for the target table?

```
4060 2023-12-11 18:11:35.972 [pool-1-thread-9] WARN com.clickhouse.jdbc.parser.ClickHouseSqlParser  - Parse error at line 1, column 13.  Encountered: transaction. If you believe the SQL is valid, please feel free to open an issue on Github with this warning and the following SQL attached.
insert into transaction(`id`,`date_created`,`date_updated`,`_sign`,`_version`) 
select `id`,`date_created`,`date_updated`,`_sign`,`_version`
from input('`id` Int32,`date_created` String,`date_updated` String,`_sign` Int8,`_version` UInt64')
```
sink-connector-lightweight used
Thanks!

**Comment by aadant** [comment]
@subkanthi  the fix is simple, just escape the table name :-)

**Comment by Selfeer** [comment]
The issue was verified by the Altinity QA team and marked as `qa-verified`.

Build used for testing: `altinityinfra/clickhouse-sink-connector:443-ea823c59644963cf752acef3987701a134cb6906-lt`

- Automated TestFlows tests were added to the `develop` branch: https://github.com/Altinity/clickhouse-sink-connector/blob/develop/sink-connector-lightweight/tests/integration/tests/table_names.py
- Requirements for the ClickHouse Sink Connector Lightweight were updated.
