### ISSUE TITLE
Support for calculated columns

### ISSUE THREAD

**Issue by aadant** [Altinity/clickhouse-sink-connector#429]
MySQL table schema can have generated columns which are not understood by CH.

Let us fix this in 2 steps :

1.  the DDL translation should convert generated columns into ALIAS columns

- clickhouse_loader.py
- sink-connector schema java converter

3. if the calculated expression is not understood by CH, it should be overridable (see schema overrides)

Example column :
```
`concat_key` varchar(1000) COLLATE latin1_general_cs GENERATED ALWAYS AS (concat(one, '-', two) VIRTUAL,

```

https://dev.mysql.com/doc/refman/8.0/en/create-table-generated-columns.html

MySQL / Postgres should be supported.

**Comment by aadant** [comment]
python utilities now support generated columns see https://github.com/Altinity/clickhouse-sink-connector/pull/426/files

**Comment by Selfeer** [comment]
The issue was verified by the Altinity QA team and marked as qa-verified.

Build used for testing: `altinityinfra/clickhouse-sink-connector:443-678d8ae2567c2c1d89f5430fa57ede619d6ea851-lt`

Automated TestFlows tests were added to the develop branch:
https://github.com/Altinity/clickhouse-sink-connector/blob/develop/sink-connector-lightweight/tests/integration/tests/calculated_columns.py

Requirements for the ClickHouse Sink Connector Lightweight were updated.
