### ISSUE TITLE
Support source tables with is_deleted columns

### ISSUE THREAD

**Issue by subkanthi** [Altinity/clickhouse-sink-connector#431]
There are possibilities where the source table(MySQL/PostgreSQL) could have columns named as `_sign` or `is_deleted`. 
To support this, there are 2 possible fixes.
1) Configuration variable to define the column name 
2) Dynamically check for existing columns and rename the generated `_sign` , `is_deleted` columns.

**Comment by subkanthi** [comment]
Implementation Details:
- CREATE TABLE: When a DDL is received from MySQL, if there is a `is_deleted` column from MySQL, change the replacingmergetree column to `_is_deleted`
- CDC Payload: Retrieve the `is_deleted` column for RMT from `system.tables` and use that to mark deleted rows.

**Comment by Selfeer** [comment]
The issue was verified by the Altinity QA team and marked as `qa-verified`.

Build used for testing: `altinityinfra/clickhouse-sink-connector:443-14a14ba5c18fb3bc9f57c48d9a5079d4d6fe15e8-lt`

Automated TestFlows tests were added to the develop branch: 
https://github.com/Altinity/clickhouse-sink-connector/blob/develop/sink-connector-lightweight/tests/integration/tests/is_deleted.py
 
Requirements for the ClickHouse Sink Connector Lightweight were updated.
