### ISSUE TITLE
Added support for multiple databases - MySQL

### ISSUE THREAD

**Issue by subkanthi** [Altinity/clickhouse-sink-connector#531]
Debezium connectors supports multiple databases use this configuration variable
`"database.include.list"`, where a list of databases can be provided.

But currently Sink connector only supports writing the results to a single database.
```
clickhouse.server.database: "test"
```
This issue is to add support for multiple databases so we could replicate multiple MySQL databases to multiple CH databases using one sink connector process.

**Comment by TruongNT95** [comment]
I got the same problem with kafka sink connector. I have 700+ databases, each database has 20+ tables stored in kafka topic follow structure :
db1.table1, db1.table2,db1.table3....
db2.table1, db2.table2,db2.table3....
db3.table1, db3.table2, db3.table3....
....
I am looking for a solution to map all databases to Clickhouse with only one connector. Do you have any solution for this problem? Something to solve  like "topics.regex" of Debezium

**Comment by subkanthi** [comment]
> I got the same problem with kafka sink connector. I have 700+ databases, each database has 20+ tables stored in kafka topic follow structure : db1.table1, db1.table2,db1.table3.... db2.table1, db2.table2,db2.table3.... db3.table1, db3.table2, db3.table3.... .... I am looking for a solution to map all databases to Clickhouse with only one connector. Do you have any solution for this problem? Something to solve like "topics.regex" of Debezium

Hi @TruongNT95 , currently the limitation is we only support one ClickHouse destination database. We are working on this feature first for the lightweight version, we will work on Kafka support after that.

**Comment by Selfeer** [comment]
The issue was verified by the Altinity QA team and marked as `qa-verified`.

The build used for testing: `altinityinfra/clickhouse-sink-connector:548-574cb9ba581caf008239dda2f7328f88697414bf-lt`

The change doesn't break any existing TestFlows regression tests, additionally specific checks were added:

- Running ALTER statements on multiple databases.
- Running ALTER statements concurrently.
- Check INSERT-s are replicated on destination database when we have more than one database.
- Check replication works when we have N number of databases and we populate each table on each database with values (checked with 10, 100 and 250 databases)
- Running ALTERS, INSERTS, DELETES and other actions in parallel on a source database.
- Creating tables on different databases but with the same name (different variations of this check were performed)
- Check combinations with `{database}.{table}` and just `{table}`

These and other check were checked both on **RMT** and **RRMT** engines.
